// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAsvYnzQVI058XdoPx7SVqLosgsrPrNA8',
    appId: '1:145724227456:web:b98f843b289f3c09438b65',
    messagingSenderId: '145724227456',
    projectId: 'my-track-time-riverpod',
    authDomain: 'my-track-time-riverpod.firebaseapp.com',
    storageBucket: 'my-track-time-riverpod.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBheCVPjjqZ78ELMLxFJUYrJnGVxAQUXkM',
    appId: '1:145724227456:android:2114ccf99c10caf6438b65',
    messagingSenderId: '145724227456',
    projectId: 'my-track-time-riverpod',
    storageBucket: 'my-track-time-riverpod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJqZAcJEupn7312x38k9bznv8DUlwgLbc',
    appId: '1:145724227456:ios:b976707d34c46e6c438b65',
    messagingSenderId: '145724227456',
    projectId: 'my-track-time-riverpod',
    storageBucket: 'my-track-time-riverpod.appspot.com',
    iosClientId: '145724227456-qnguea8tab4bbhbrdl3akqmafec0usqd.apps.googleusercontent.com',
    iosBundleId: 'com.example.trackTimeRiverpod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJqZAcJEupn7312x38k9bznv8DUlwgLbc',
    appId: '1:145724227456:ios:b976707d34c46e6c438b65',
    messagingSenderId: '145724227456',
    projectId: 'my-track-time-riverpod',
    storageBucket: 'my-track-time-riverpod.appspot.com',
    iosClientId: '145724227456-qnguea8tab4bbhbrdl3akqmafec0usqd.apps.googleusercontent.com',
    iosBundleId: 'com.example.trackTimeRiverpod',
  );
}
